addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.29")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.6.1")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.23")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.3.7")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"               % "1.0.8-0.6")
addSbtPlugin("com.typesafe.play"  % "sbt-plugin"                    % "2.6.15")
addSbtPlugin("com.typesafe.sbt"   % "sbt-gzip"                      % "1.0.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"                    % "1.1.4")

